CREATE TABLE products (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    name VARCHAR(255) NOT NULL,

    description TEXT,

    brand VARCHAR(100) NOT NULL,

    category VARCHAR(100) NOT NULL,

    price DECIMAL(10,2) NOT NULL,

    rating DECIMAL(3,2) DEFAULT 0.00,

    image_url VARCHAR(500),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);